# Generated by Django 3.0.6 on 2020-06-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
