# Generated by Django 3.0.6 on 2020-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
