# Generated by Django 3.0.6 on 2020-06-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_beer_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='pubname',
            field=models.TextField(null=True),
        ),
    ]
