# Generated by Django 3.0.6 on 2020-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_beer_pubname'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcohol',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='beername',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='categorie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='taste',
            field=models.TextField(null=True),
        ),
    ]
