# Generated by Django 3.0.6 on 2020-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20200601_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='body',
        ),
    ]
