# Generated by Django 3.0.6 on 2020-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_beer_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
