# Generated by Django 3.0.6 on 2020-06-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_beer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='title',
        ),
    ]
