# Generated by Django 3.0.6 on 2020-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_beer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='categorie',
            new_name='information',
        ),
    ]
