# Generated by Django 3.0.6 on 2020-06-09 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150, verbose_name='댓글!')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150, verbose_name='대댓글')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Menulist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50, verbose_name='메뉴')),
                ('Publist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Publist')),
            ],
        ),
        migrations.CreateModel(
            name='Menudetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.CharField(max_length=50, verbose_name='펍이름')),
                ('beername', models.CharField(max_length=50, verbose_name='맥주이름')),
                ('beerimage', models.ImageField(upload_to='', verbose_name='이미지')),
                ('taste', models.TextField(verbose_name='맛')),
                ('information', models.TextField(verbose_name='정보')),
                ('price', models.CharField(max_length=30, verbose_name='가격')),
                ('alcohol', models.CharField(max_length=30, verbose_name='알콜도수')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('menulist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Menulist')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Publist'),
        ),
    ]
