# Generated by Django 3.0.6 on 2020-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetail',
            name='beerimage',
            field=models.ImageField(null=True, upload_to='', verbose_name='이미지'),
        ),
    ]
