# Generated by Django 3.0.7 on 2020-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_recomment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=120, verbose_name='댓글!'),
        ),
    ]
