# Generated by Django 3.0.6 on 2020-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20200603_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetail',
            name='beerimage',
            field=models.ImageField(upload_to='', verbose_name='이미지'),
        ),
    ]
