# Generated by Django 3.0.7 on 2020-06-03 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0004_auto_20200603_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudetail',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
