# Generated by Django 2.2.7 on 2020-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_menudetail_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menudetail',
            old_name='tasate',
            new_name='taste',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=150, verbose_name='댓글!'),
        ),
    ]
